### ISSUE TITLE
cannot use pyenv-mode on windows7.

### ISSUE THREAD

**Issue by nasoundead** [proofit404/pyenv-mode#28]
Excuse, i am new to use pyenv-mode with Spacemacs python layer.
1. Need to install pyenv(https://github.com/pyenv/pyenv) first? 
2. pyenv-mode is a emacs package depend on the pyenv?
So, maybe pyenv do not support windows, and then i cannot use pyenv-mode on windows too?

**Comment by proofit404** [comment]
Hi!

Nearly all pyenv-mode do is setting few emacs variables for python-mode. I guess since pyenv itself is written in bash, it can be used with new linux subsystem on windows. If you running emacs from that subsystem, pyenv-mode should works as expected.

Otherwise, I'm afraid you can't use pyenv and pyenv-mode with native python build for windows.

Hope this helps.

Regards, Artem.

**Comment by nasoundead** [comment]
Thank you for your answer, I got it
